spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://218.192.170.29/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
  jpa:
    show-sql: true
